### PR TITLE
Update gradle-4.4 

### PR DESCRIPTION
**Pull request by EvertonMelo**
Hi, 

address Bounty: NDI55N-OEHLZS-PNIZEU-L2XU7S-3477UZ-PBNZ5Q-5BPQ

update Grable-4.4 
utils:
    Automatic project synchronization
    Runtime classpath separation
    Java 9 compatibility for Buildship plugins
++++++++++++++++++++++++++++++++++
desible support  new compiler; 
enableD8 = False; 
and #305 too

font: https://newsletter.gradle.com/2017/12

### CODE REVIEW

**Comment by EvertonMelo** [comment]
After Deploy & more tests, resolution of bugs:

#268 
#288 
#287 
#280 
#275 
#270 
#269 
#238 

mentioned, please send feedback

**Comment by kekkyojin** [comment]
Take a seat while you are waiting. I made a few PR, and still waiting since April. I consider this project almost dead. No new commits since January. Some of the PR are inoquous, including your ISSUE one. But no comments from the team.

**Comment by EvertonMelo** [comment]
@kekkyojin 

Thank you for expressing an unsolicited opinion.

but: "Tarde venientibus ossa."

**Comment by kekkyojin** [comment]
Your PR wasn't solicited, neither.

I expressed my opinion freely just as you can do.

There has passed seven months since latest commit. No user should be using this app as developers are clearly not showing interest in keeping it updated.

You are still free to keep posting more PR, but I am also free to warn you that you should not expect those PR to be merged soon. I am just warning you, not asking you not to participate.

**Comment by cryptoBeliever** [comment]
As far as I know there is running work and redesign on this repository internally so it's possible that it will be never merged.

**Comment by kekkyojin** [comment]
Look. @EvertonMelo. That's what I said. May you ask me to shut up now?

**Comment by cryptoBeliever** [comment]
Because I'm not a developer in this project and I don't have access to close anything here. Just know that there is ongoing work not already pushed to this repo so it can change a lot.

**Pull request closed without merging**
