### PR TITLE
Create ISSUE for NemAndroidApp

### PR DESCRIPTION
**Pull request by EvertonMelo**
checklist for Open ISSUE on Repository NEMAndroidApp.

### CODE REVIEW

**Comment by EvertonMelo** [comment]
@kekkyojin 

**Agere non loqui**

**Comment by kekkyojin** [comment]
I can see that being possitive on you results are the same. Did you see I "Aproved" your PR? Now there is someone who revieewed your change. Let's see how many time passes until the PR is merged into the repository. You are fighting the wrong person.

Also, speaking in latin doesn't make you smarter.

**Comment by EvertonMelo** [comment]
@saulgray 

please, check status for the ISSUE

**Comment by EvertonMelo** [comment]
okay

**Pull request closed without merging**
